# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

distinct_terms = []

for a in range(2,101):
    for b in range(2, 101):
        term = a**b
        if term not in distinct_terms:
            distinct_terms.append(term)

print("Number of distinct terms = " + str(len(distinct_terms)))
